### ISSUE TITLE
Feature suggestion: Add sounds for certain events

### ISSUE THREAD

**Issue by ivnc** [ibrahim-s/trainingNvdaCommands#1]
A Spanish-speaking user has commented through a mailing list that it would be interesting to add some sounds triggered by events such as scoring a point, providing a wrong answer or winning the game, to make it to look more like a game. He suggests sounds as these, which he has sent us by email:

[tkbcmd-sonidos.zip](https://github.com/ibrahim-s/trainingNvdaCommands/files/2769410/tkbcmd-sonidos.zip)

Regards.

**Comment by ibrahim-s** [comment]
Hi,
thank you for suggestion
I downloaded the sound file you provided
and I will try to include these sounds in the addon.
regards.

On 17-Jan-19 5:48 PM, Iván Novegil wrote:

A Spanish-speaking user has commented through a mailing list that it would be interesting to add some sounds triggered by events such as scoring a point, providing a wrong answer or winning the game, to make it to look more like a game. He suggests sounds as these, which he has sent us by email:
Uploading tkbcmd-sonidos.zip…

Regards.

**Comment by ivnc** [comment]
Implementation confirmed by the user in 1.2-dev. He thanks you for accepting his suggestion.

Regards.

**Comment by ibrahim-s** [comment]
well, thank you.
regards.

On 21-Jan-19 10:31 AM, Iván Novegil wrote:

Implementation confirmed by the user in 1.2-dev. He thanks you for accepting his suggestion.

Regards.

**Comment by cary-rowen** [comment]
Hello, may I ask whether the sleep during the sound playing process can be cancelled. People often don’t like being interrupted by such short-lived rocks, and I think these sounds take too long.I have translated it into simplified Chinese and I am considering making a PR.
Thanks.

**Comment by ibrahim-s** [comment]
hello,
really I now do not know a way to cancel the sounds during playing
but may be I can try something if you find it suitable,
I may be can make settings pane for the addon
and make a choice in the setting to enable the sounds or disable them, 
is this satisfies you?
thank you.

**Comment by cary-rowen** [comment]
Sorry, maybe I didn't express it clearly. The sound played was good, making it look more like a game. However, there was a short sleep during the sound playing, making the keyboard unresponsive. I checked the code, in line 162, line 167, and line 175 in game.py.

Comment out these lines to get a better user experience.
Thanks for the add-on

**Comment by ibrahim-s** [comment]
Yes, I agree with you
but if we omit this sleep line
the sound playing will overlap with the voice of the screen reader
and the user cannot understand the beginning of the next question
and really that was the reason for putting that sleep time.
anyway, happy for your interest and remarks.
kind regards

**Comment by cary-rowen** [comment]
Happy for your patient response,
Many users in China and I generally think that the current voice time is too long. During the answering process, we pay more attention to how to complete the next question quickly. The voice is relatively not that important. I think we can choose a shorter voice. Replace existing sound files.
I will contribute a few sound files, If you think it is inappropriate, I am Sorry for my presumption.
@ibrahim-s @ivnc

**Comment by cary-rowen** [comment]
[sounds.zip](https://github.com/ibrahim-s/trainingNvdaCommands/files/5971770/sounds.zip)

**Comment by ibrahim-s** [comment]
OK, my friend
I will be happy for any contribution
let me just test them
I know that the previous sounds was long a little bit
but really I am not good in the region of sounds and adjusting them
and if I find the new sounds will do the job
I will be very happy to remove the sleeping time then.
my kind regards
