### ISSUE TITLE
pot-translation template

### ISSUE THREAD

**Issue by Futyn-Maker** [ibrahim-s/trainingNvdaCommands#2]
Hello!

It would be nice if You add a translation tamplet in Your repo. I want to translate the addon, but i don't know where can I find the pot-tamplet.

**Comment by ibrahim-s** [comment]
Hello
Thank you for your interest of the addon
well, this is the pot file :
https://www.dropbox.com/s/9nnxvj091tdhv0u/trainingKeyboardCommands.zip?dl=1
you can send it for me,say what language, and I will merge it in the addon
regards

**Comment by Futyn-Maker** [comment]
Thanks
